{
  "formatVersion": "1.1",
  "component": {
    "group": "com.caomei.clerk",
    "module": "backend-api",
    "version": "0.2.0-beta.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.4.jar",
          "url": "backend-api-0.2.0-beta.4.jar",
          "size": 1822899,
          "sha512": "905944d368836b85c7811bf3a2c2e42289e42291758a8c5b4e2ccbe5d483ab48e80153dfe62f8b536291c5b47b1594f07c86d781b0e3e17a9c4eea3efb80edd6",
          "sha256": "2a545e24bf2c9fd351fec32d6916874f239000be61c6074e98c0512173b3ece2",
          "sha1": "b1e50e83bffc0bd1f48c044f88e6161867752672",
          "md5": "826431822e2c4dfb364630d273024864"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.openapitools",
          "module": "jackson-databind-nullable",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.76"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.4.jar",
          "url": "backend-api-0.2.0-beta.4.jar",
          "size": 1822899,
          "sha512": "905944d368836b85c7811bf3a2c2e42289e42291758a8c5b4e2ccbe5d483ab48e80153dfe62f8b536291c5b47b1594f07c86d781b0e3e17a9c4eea3efb80edd6",
          "sha256": "2a545e24bf2c9fd351fec32d6916874f239000be61c6074e98c0512173b3ece2",
          "sha1": "b1e50e83bffc0bd1f48c044f88e6161867752672",
          "md5": "826431822e2c4dfb364630d273024864"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.4-sources.jar",
          "url": "backend-api-0.2.0-beta.4-sources.jar",
          "size": 811063,
          "sha512": "92c6bb61b56c3f310cdac184e1e616cd72cd9b70938bbfcf1bcb8c007892a21a3eb3cdc7a9f552cf376d19bd7d1964d3dfd1646da2d69552b42867a051c6e1f1",
          "sha256": "26d34c8cd0deeb8614daa902afa09efbe6c1d1d0fb34b20570ba6281de13fbe4",
          "sha1": "f441fac36b3d89adf69d97f512c3d3de0e69d777",
          "md5": "16c4fbd067c061d71a8eeed405ead021"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.4-javadoc.jar",
          "url": "backend-api-0.2.0-beta.4-javadoc.jar",
          "size": 4088823,
          "sha512": "d8d409f45a0d8c7d53fd196940c8918b324f20a1d068437c985807cc6a4a0ef35ddd0f6900c1eb24d14f274c0eec13e5764784ff5ae9156aba3873d6f8613a84",
          "sha256": "ccaf4d5249f5d9494042ef81082f60522baa41734fc819535aa34d51841399ad",
          "sha1": "5b041dffcba5da7dd9c48a88ea3d4c62771c74a8",
          "md5": "8a4dfd36657c77feba46fa10df7b7780"
        }
      ]
    }
  ]
}
