{
  "formatVersion": "1.1",
  "component": {
    "group": "com.caomei.clerk",
    "module": "backend-api",
    "version": "0.2.0-beta.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.2.jar",
          "url": "backend-api-0.2.0-beta.2.jar",
          "size": 1822235,
          "sha512": "9c7c77658be4a15a0d3c1b287fe4cea14fe5a4c6b2b9435d88bb31d595fa864cddb49647e9365bd69764e7c5119f934cb8352de8d10fd6588243ac9f4e26d441",
          "sha256": "9b1ad98448a9d848a84ba50d0a6233f8b3518aa0b79c06fd53acefdb4a6a1306",
          "sha1": "88fb0116bc6d301bb230377ba39a1f819c9c9080",
          "md5": "5c44742825644e5c02bcb1b45da88d2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.openapitools",
          "module": "jackson-databind-nullable",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.76"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.2.jar",
          "url": "backend-api-0.2.0-beta.2.jar",
          "size": 1822235,
          "sha512": "9c7c77658be4a15a0d3c1b287fe4cea14fe5a4c6b2b9435d88bb31d595fa864cddb49647e9365bd69764e7c5119f934cb8352de8d10fd6588243ac9f4e26d441",
          "sha256": "9b1ad98448a9d848a84ba50d0a6233f8b3518aa0b79c06fd53acefdb4a6a1306",
          "sha1": "88fb0116bc6d301bb230377ba39a1f819c9c9080",
          "md5": "5c44742825644e5c02bcb1b45da88d2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.2-sources.jar",
          "url": "backend-api-0.2.0-beta.2-sources.jar",
          "size": 810929,
          "sha512": "0567512cd3ce43c5aeac98778e66f1f66cf7850780ca2ad9d81194d5cf74a5f90a424e324fef5197e5d32845d8f43d6299674a4c3b11f1e0706982b50a5e59b3",
          "sha256": "9109227461101ff2d517f9bad9f73dab2e7466b0e875d77320876d8da5e9b8d1",
          "sha1": "ab97a9d1b99871b88e82718b2d2caee469d8235e",
          "md5": "4c2e302ac2f4ee555cffbdd25cce4292"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.2-javadoc.jar",
          "url": "backend-api-0.2.0-beta.2-javadoc.jar",
          "size": 4087949,
          "sha512": "da21f57ad304b70b9005efd32349d687d9b538c10b4c40dbbe7b2c893721450c024ec78fc6f100de4eb68f1f95edd96014c7aa3969c57d4a6a914682dd35ac24",
          "sha256": "12a505b65e936911e677a9b17e953edcf37775167f7b78869aeb76ec9de44720",
          "sha1": "b2a0974089bda29a7f54f862ea06c90da60bfcac",
          "md5": "3991a6f673c4a7f1f506fa907f542b9f"
        }
      ]
    }
  ]
}
