{
  "formatVersion": "1.1",
  "component": {
    "group": "com.caomei.clerk",
    "module": "backend-api",
    "version": "0.2.0-beta.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.2.jar",
          "url": "backend-api-0.2.0-beta.2.jar",
          "size": 1822036,
          "sha512": "5896a86a163f51540d55a25964a55a5b9e8ef4cba804885a9c25a597ae1d852935b264449f91f9f940f3f35bc3bc7d11800c2c436f9061d85633239ebb48ed2e",
          "sha256": "60d23d75caf94c891adb34fc97399629e452b51adf9d7f187df47ff298c99465",
          "sha1": "1ea19501939c49526f4e9c1c6183e376a33b15ec",
          "md5": "82afc44c840c99b7e1111aa8ce29979d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.openapitools",
          "module": "jackson-databind-nullable",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.76"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.2.jar",
          "url": "backend-api-0.2.0-beta.2.jar",
          "size": 1822036,
          "sha512": "5896a86a163f51540d55a25964a55a5b9e8ef4cba804885a9c25a597ae1d852935b264449f91f9f940f3f35bc3bc7d11800c2c436f9061d85633239ebb48ed2e",
          "sha256": "60d23d75caf94c891adb34fc97399629e452b51adf9d7f187df47ff298c99465",
          "sha1": "1ea19501939c49526f4e9c1c6183e376a33b15ec",
          "md5": "82afc44c840c99b7e1111aa8ce29979d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.2-sources.jar",
          "url": "backend-api-0.2.0-beta.2-sources.jar",
          "size": 810964,
          "sha512": "8819bf18b554116dbf0ac7f3645787105bce1816932e5f88096db4a1fd1692d3c23ce355b8ac0c678679e6d69d2acefbff8dc950b1482c9965e0899ef860fe15",
          "sha256": "638aaf7aff37b50f1c1999cf6bb55e635798db8503021514153b1d27229e2cd1",
          "sha1": "30b98680580868a362df041703e2842faeec430a",
          "md5": "a5caba57d53d551708d5938094b16bfb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.2-javadoc.jar",
          "url": "backend-api-0.2.0-beta.2-javadoc.jar",
          "size": 4088064,
          "sha512": "b4665ce98ae080b031c31171f09873a660c4aff0be4e8d472f94d6f393b67cfd4a3a08071c7b1f4a22fa71457e8021499347c6faea9bef2efdf57c852ddf56d7",
          "sha256": "6613b47adcd96785b5a9f2fd7c0753b41fd5f52ddf3d9882170322e37946fbc4",
          "sha1": "1906d0ff5159c0e8029d5445c1eed0a3841243df",
          "md5": "10b1eeb0f59900bd19c3be95b9c3a941"
        }
      ]
    }
  ]
}
