{
  "formatVersion": "1.1",
  "component": {
    "group": "com.caomei.clerk",
    "module": "backend-api",
    "version": "0.2.0-beta.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.3.jar",
          "url": "backend-api-0.2.0-beta.3.jar",
          "size": 1822369,
          "sha512": "f82d6d1d8c9333d9398dc981d000bea409359e6bf1130a9befee7a9d35ae8bb112162e6af3f6e8ece6df1aaab6210125c4b60136385654706673609bdc581a0b",
          "sha256": "f7d602a0e5dcf452cce28bbc43b45f09aa0d3579e3d7577715b93e9a6aa90818",
          "sha1": "5256e06c2fcaaaaf44707baf7529ab88f80ece43",
          "md5": "8a2b7ebc7b6bfdd643512cd0e54e3d63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.openapitools",
          "module": "jackson-databind-nullable",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.76"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.3.jar",
          "url": "backend-api-0.2.0-beta.3.jar",
          "size": 1822369,
          "sha512": "f82d6d1d8c9333d9398dc981d000bea409359e6bf1130a9befee7a9d35ae8bb112162e6af3f6e8ece6df1aaab6210125c4b60136385654706673609bdc581a0b",
          "sha256": "f7d602a0e5dcf452cce28bbc43b45f09aa0d3579e3d7577715b93e9a6aa90818",
          "sha1": "5256e06c2fcaaaaf44707baf7529ab88f80ece43",
          "md5": "8a2b7ebc7b6bfdd643512cd0e54e3d63"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.3-sources.jar",
          "url": "backend-api-0.2.0-beta.3-sources.jar",
          "size": 810959,
          "sha512": "95183ad460d2e5744d66f1fdb371fc8c5ce1e16841ba0f16d2b47d2fbee9eb54a8ef9eb5b8f5142d4b479363505d215ec7e87505488dcd6bbb3be4ac15538f07",
          "sha256": "63938239d7c5d18c17c7f5f627ebef1e77c5d60727481bd7f2715c7940ac3280",
          "sha1": "80f375e968dfc353470817217c0eee8859124818",
          "md5": "771bb6bf57ce6a1c370ddaf1bfbfe9fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.3-javadoc.jar",
          "url": "backend-api-0.2.0-beta.3-javadoc.jar",
          "size": 4088090,
          "sha512": "ddfda3777c71c39d6cfe5042c0779a807382d66c3437f190377119f7031378b087cc2ae5c93069d3783dca83c6315105accf40aafbcfe921084c9f4e24a8a429",
          "sha256": "1cf13725dd210c77fe7a57284ed18b1a2b863e391ec6f79824d98a033b5aa6cc",
          "sha1": "7aff265a63b55f84231ad516a155dfad6fc448d0",
          "md5": "7fa95319720cdbb6b906cc21404e1b72"
        }
      ]
    }
  ]
}
