{
  "formatVersion": "1.1",
  "component": {
    "group": "com.caomei.clerk",
    "module": "backend-api",
    "version": "0.2.0-beta.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.6.jar",
          "url": "backend-api-0.2.0-beta.6.jar",
          "size": 1822367,
          "sha512": "063749277ac45a479f0d6dd70548f5710cfcb20138ff827b3b89b11f16e32ef25a1a64b745ca2dd3449ef50802fe881f79da873ca3bf6df184f86ab5d1113025",
          "sha256": "db9bb5158d927cab8f91e566fafa6a1b151dcaf397a474f7b712bec5322ff4d3",
          "sha1": "1cff54bec057d48ea5b040d921ab5dbf4e28221f",
          "md5": "4c26a9c781c3966e25e9c007a9617779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.openapitools",
          "module": "jackson-databind-nullable",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.76"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        }
      ],
      "files": [
        {
          "name": "backend-api-0.2.0-beta.6.jar",
          "url": "backend-api-0.2.0-beta.6.jar",
          "size": 1822367,
          "sha512": "063749277ac45a479f0d6dd70548f5710cfcb20138ff827b3b89b11f16e32ef25a1a64b745ca2dd3449ef50802fe881f79da873ca3bf6df184f86ab5d1113025",
          "sha256": "db9bb5158d927cab8f91e566fafa6a1b151dcaf397a474f7b712bec5322ff4d3",
          "sha1": "1cff54bec057d48ea5b040d921ab5dbf4e28221f",
          "md5": "4c26a9c781c3966e25e9c007a9617779"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.6-sources.jar",
          "url": "backend-api-0.2.0-beta.6-sources.jar",
          "size": 810959,
          "sha512": "36a044347df4d4e128ec05bf6578616f5abb5bdf9d0b52aa875f13c5b188507626a9f0353836d49cfa3a9755911cc4f27e058fc7f1b53819dbcd6346ec4f243d",
          "sha256": "21096b47e1f653768c91420d6a19bf62e3444bf5ca950c665c0deaca004e8436",
          "sha1": "276059e4b0a2b9d0f765937fa6947979429221cb",
          "md5": "b5e84fe54a4006539e43c4ef91bdd68e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-api-0.2.0-beta.6-javadoc.jar",
          "url": "backend-api-0.2.0-beta.6-javadoc.jar",
          "size": 4088281,
          "sha512": "5e95cb75f9560c581ddc6ba5ca02f2cb09f174a856d80232b7eee3104ed2ab1b8590c5f958ac76008ab8cec90e2cd29345465c3a0d080f34a3cca8261e94b56d",
          "sha256": "4b4d454de57a2bcd0a4dcf91fca78ace7ba47094d4cb69874852c9051e473717",
          "sha1": "f3513661434a9b8cc9a68d30b2be39c26ced3c3f",
          "md5": "ba1105e250ff47046ef7e48189048561"
        }
      ]
    }
  ]
}
